const domainToIcon: Record<string, string> = {
  "youtube.com": "Youtube",
  "youtu.be": "Youtube",
  "twitter.com": "Twitter",
  "x.com": "Twitter",
  "instagram.com": "Instagram",
  "linkedin.com": "LinkedIn",
  "github.com": "github",
  "facebook.com": "Facebook",
  "fb.com": "Facebook",
  "messenger.com": "Facebook_Messenger",
  "discord.com": "Discord",
  "discord.gg": "Discord",
  "tiktok.com": "TikTok",
  "twitch.tv": "Twitch",
  "whatsapp.com": "Whatsapp",
  "wa.me": "Whatsapp",
  "telegram.org": "Telegram",
  "t.me": "Telegram",
  "snapchat.com": "Snapchat",
  "pinterest.com": "Pinterest",
  "reddit.com": "Reddit",
  "spotify.com": "Spotify",
  "soundcloud.com": "SoundCloud",
  "tumblr.com": "Tumblr",
  "deviantart.com": "Deviantart",
  "artstation.com": "ArtStation",
  "patreon.com": "Patreon",
  "ko-fi.com": "Ko_Fi",
  "paypal.com": "PayPal",
  "paypal.me": "PayPal",
  "amazon.com": "Amazon",
  "amzn.to": "Amazon",
  "netflix.com": "Netflix",
  "primevideo.com": "Amazon_Prime",
  "steampowered.com": "Steam",
  "steam.com": "Steam",
  "notion.so": "Notion",
  "trello.com": "Trello",
  "slack.com": "Slack",
  "toggl.com": "Toggl",
  "todoist.com": "Todoist",
  "evernote.com": "Evernote",
  "miro.com": "Miro",
  "zoom.us": "Zoom",
  "skype.com": "Skype",
  "tinder.com": "Tinder",
  "letterboxd.com": "Letterboxd",
  "airbnb.com": "AirBnB",
  "booking.com": "Booking",
  "uber.com": "Uber",
  "ubereats.com": "Uber_Eats",
  "deliveroo.com": "Deliveroo",
  "glovoapp.com": "Glovo",
  "pedidosya.com": "PedidosYa",
  "mercadolibre.com": "Mercadolibre",
  "mercadopago.com": "Mercadopago",
  "idealista.com": "Idealista",
  "outlook.com": "Outlook",
  "gmail.com": "Gmail",
  "drive.google.com": "Google_Drive",
  "maps.google.com": "Google_Maps",
  "photos.google.com": "Google_Photos",
  "calendar.google.com": "Google_Calendar",
  "docs.google.com": "Google_Docs",
  "sheets.google.com": "Google_Sheets",
  "slides.google.com": "Google_Slides",
  "forms.google.com": "Google_Forms",
  "translate.google.com": "Google_Translate",
  "play.google.com": "Google_Playstore",
  "keep.google.com": "Google_Keep",
  "mail.google.com": "Gmail",
  "firefox.com": "Firefox",
  "mozilla.org": "Firefox",
  "opera.com": "Opera",
  "vivaldi.com": "Vivaldi",
  "apple.com": "Safari",
  "linkwave.ai": "linkwave",
  "wikipedia.org": "Wikipedia",
  "duolingo.com": "Duolingo",
  "myfitnesspal.com": "My_Fitness_Pal",
  "itch.io": "Itch_io",
  "cash.app": "PayPal",
  "venmo.com": "PayPal",
  "flickr.com": "Twitter",
  "dribbble.com": "Notion",
  "behance.net": "Notion",
  "figma.com": "Notion",
  "vimeo.com": "Youtube",
  "rumble.com": "Youtube",
  "odysee.com": "Youtube",
  "dailymotion.com": "Youtube",
  "bitchute.com": "Youtube",
  "brighteon.com": "Youtube",
  "lbry.com": "Youtube",
  "twitpic.com": "Twitter",
  "twitcasting.tv": "Twitch",
  "kick.com": "Twitch",
  "streamyard.com": "Twitch",
  "restream.io": "Twitch",
  "trovo.live": "Twitch",
  "dlive.tv": "Twitch",
  "streamelements.com": "Twitch",
  "streamlabs.com": "Twitch",
  "nightbot.tv": "Twitch",
  "moobot.tv": "Twitch",
  "threads.net": "Instagram",
  "hive.social": "Instagram",
  "vsco.co": "Instagram",
  "500px.com": "Instagram",
  "ello.co": "Instagram",
  "pexels.com": "Pinterest",
  "unsplash.com": "Pinterest",
  "imgur.com": "Reddit",
  "giphy.com": "Reddit",
  "tenor.com": "Reddit",
  "goodreads.com": "Reddit",
  "quora.com": "Reddit",
  "stackoverflow.com": "Reddit",
  "news.ycombinator.com": "Reddit",
  "hackernews.com": "Reddit",
  "producthunt.com": "Twitter",
  "indiehackers.com": "Twitter",
  "bluesky.com": "Twitter",
  "mastodon.social": "Twitter",
  "parler.com": "Twitter",
  "gab.com": "Twitter",
  "post.news": "Twitter",
  "gettr.com": "Twitter",
  "truthsocial.com": "Twitter",
  "likee.com": "TikTok",
  "kwai.com": "TikTok",
  "triller.com": "TikTok",
  "bigo.tv": "Twitch",
  "periscope.tv": "Twitter",
  "spaces.com": "Twitter",
  "signal.org": "Telegram",
  "matrix.org": "Discord",
  "guilded.gg": "Discord",
  "teamspeak.com": "Discord",
  "irccloud.com": "Telegram",
  "wire.com": "Whatsapp",
  "wechat.com": "Whatsapp",
  "line.me": "Whatsapp",
  "viber.com": "Whatsapp",
  "groupme.com": "Whatsapp",
  "nextdoor.com": "Facebook",
  "meetup.com": "Facebook",
  "eventbrite.com": "Facebook",
  "fb.watch": "Facebook",
  "imdb.com": "Netflix",
  "rottentomatoes.com": "Netflix",
  "trakt.tv": "Netflix",
  "plex.tv": "Netflix",
  "crunchyroll.com": "Netflix",
  "hulu.com": "Netflix",
  "hbomax.com": "Netflix",
  "max.com": "Netflix",
  "disneyplus.com": "Netflix",
  "peacocktv.com": "Netflix",
  "paramountplus.com": "Netflix",
  "appletv.com": "Netflix",
  "funimation.com": "Netflix",
  "hidive.com": "Netflix",
  "applemusic.com": "Spotify",
  "music.apple.com": "Spotify",
  "pandora.com": "Spotify",
  "iheart.com": "Spotify",
  "shazam.com": "Spotify",
  "tidal.com": "Spotify",
  "deezer.com": "Spotify",
  "genius.com": "SoundCloud",
  "bandcamp.com": "SoundCloud",
  "mixcloud.com": "SoundCloud",
  "audiomack.com": "SoundCloud",
  "last.fm": "SoundCloud",
  "medium.com": "Google_Chrome",
  "substack.com": "Google_Chrome",
  "wordpress.com": "Google_Chrome",
  "blogger.com": "Google_Chrome",
  "wixsite.com": "Google_Chrome",
  "squarespace.com": "Google_Chrome",
  "weebly.com": "Google_Chrome",
  "carrd.co": "Google_Chrome",
  "linktr.ee": "Google_Chrome",
  "beacons.ai": "Google_Chrome",
  "taplink.cc": "Google_Chrome",
  "bio.link": "Google_Chrome",
  "lnk.bio": "Google_Chrome",
  "hopp.bio": "Google_Chrome",
  "bento.me": "Google_Chrome",
  "about.me": "Google_Chrome",
  "shopify.com": "Amazon",
  "etsy.com": "Amazon",
  "aliexpress.com": "Amazon",
  "ebay.com": "Amazon",
  "olx.com": "Amazon",
  "aws.amazon.com": "Amazon",
  "teams.microsoft.com": "Microsoft_Edge",
  "office.com": "Microsoft_Office",
  "onedrive.com": "Microsoft_OneDrive",
  "1drv.ms": "Microsoft_OneDrive",
  "microsoft.com": "Microsoft_Edge",
  "vscode.dev": "github",
  "codepen.io": "github",
  "codesandbox.io": "github",
  "replit.com": "github",
  "dev.to": "github",
  "gitlab.com": "github",
  "bitbucket.org": "github",
  "sourceforge.net": "github",
  "codeberg.org": "github",
  "gitea.com": "github",
  "gist.github.com": "github",
  "glitch.com": "github",
  "netlify.app": "github",
  "vercel.app": "github",
  "supabase.com": "github",
  "heroku.com": "github",
  "render.com": "github",
  "railway.app": "github",
  "fly.io": "github",
  "digitalocean.com": "github",
  "brave.com": "Battle",
  "epicgames.com": "Battle",
  "ea.com": "Battle",
  "origin.com": "Battle",
  "ubisoft.com": "Battle",
  "blizzard.com": "Battle",
  "battle.net": "Battle",
  "playstation.com": "Battle",
  "xbox.com": "Battle",
  "nintendo.com": "Battle",
  "chess.com": "Battle",
  "lichess.org": "Battle",
  "steamcommunity.com": "Steam",
  "steamusercontent.com": "Steam",
  "gog.com": "Steam",
  "canva.com": "Notion",
  "adobe.com": "Notion",
  "airtable.com": "Notion",
  "coda.io": "Notion",
  "linear.app": "Notion",
  "clickup.com": "Todoist",
  "asana.com": "Todoist",
  "monday.com": "Todoist",
  "basecamp.com": "Todoist",
  "dropbox.com": "Google_Drive",
  "box.com": "Google_Drive",
  "mega.nz": "Google_Drive",
  "icloud.com": "Google_Drive",
  "google.com": "Google",
  "bing.com": "Microsoft_Edge",
  "duckduckgo.com": "Opera",
  "yandex.com": "Google",
  "baidu.com": "Google",
  "twitchemotes.com": "Twitch",
  "fosscat.com": "Discord",
  "mumble.com": "Discord",
  "ventrilo.com": "Discord",
  "kakaotalk.com": "Whatsapp",
  "band.us": "Whatsapp",
  "fiverr.com": "PayPal",
  "upwork.com": "PayPal",
  "freelancer.com": "PayPal",
  "99freelas.com": "PayPal",
  "workana.com": "PayPal",
  "getninjas.com": "PayPal",
  "toptal.com": "LinkedIn",
  "indeed.com": "LinkedIn",
  "glassdoor.com": "LinkedIn",
  "ziprecruiter.com": "LinkedIn",
  "hashnode.com": "Google_Chrome",
  "ghost.io": "Google_Chrome",
  "cont.me": "Google_Chrome",
  "milkshake.app": "Google_Chrome",
  "allmylinks.com": "Google_Chrome",
  "solo.to": "Google_Chrome",
  "many.bio": "Google_Chrome",
  "pcloud.com": "Google_Drive",
  "studiovity.com": "Notion",
  "teamwork.com": "Todoist",
  "jira.com": "Notion",
  "confluence.com": "Notion",
  "dis.gd": "Discord",
  "discordsays.com": "Discord",
};

const domainAliases: Record<string, string[]> = {
  "Youtube": ["youtube", "yt"],
  "Twitter": ["twitter", "x", "tw"],
  "Instagram": ["instagram", "ig", "insta"],
  "LinkedIn": ["linkedin", "in"],
  "github": ["github", "gh", "git"],
  "Facebook": ["facebook", "fb"],
  "Discord": ["discord"],
  "TikTok": ["tiktok", "tt"],
  "Twitch": ["twitch"],
  "Whatsapp": ["whatsapp", "wa", "whats"],
  "Telegram": ["telegram", "tg"],
  "Snapchat": ["snapchat", "snap"],
  "Pinterest": ["pinterest", "pin"],
  "Reddit": ["reddit"],
  "Spotify": ["spotify"],
  "SoundCloud": ["soundcloud", "sc"],
  "Tumblr": ["tumblr"],
  "PayPal": ["paypal", "pp"],
  "Amazon": ["amazon"],
  "Netflix": ["netflix"],
  "Steam": ["steam"],
  "Notion": ["notion"],
  "Zoom": ["zoom"],
  "Gmail": ["gmail"],
  "Wikipedia": ["wikipedia", "wiki"],
  "Duolingo": ["duolingo"],
};

export function getIconFromUrl(url: string): string | null {
  if (!url || url.trim().length < 4) return null;

  try {
    const trimmed = url.trim();
    const hasProtocol = /^https?:\/\//i.test(trimmed);
    const fullUrl = hasProtocol ? trimmed : `https://${trimmed}`;
    const parsed = new URL(fullUrl);
    let hostname = parsed.hostname.toLowerCase();

    if (hostname.startsWith("www.")) {
      hostname = hostname.slice(4);
    }

    if (domainToIcon[hostname]) return domainToIcon[hostname];

    const parts = hostname.split(".");
    const baseDomain = parts[0];

    for (const [iconName, aliases] of Object.entries(domainAliases)) {
      if (aliases.some((a) => baseDomain === a || baseDomain.includes(a))) {
        return iconName;
      }
    }

    const matchingIcons = [
      "Youtube", "Twitter", "Instagram", "LinkedIn", "github", "Facebook",
      "Discord", "TikTok", "Twitch", "Whatsapp", "Telegram", "Snapchat",
      "Pinterest", "Reddit", "Spotify", "SoundCloud", "Tumblr", "Deviantart",
      "ArtStation", "Patreon", "Ko_Fi", "PayPal", "Amazon", "Netflix",
      "Steam", "Notion", "Trello", "Slack", "Todoist", "Evernote",
      "Zoom", "Skype", "Gmail", "Outlook", "Wikipedia", "Duolingo",
    ];

    for (const icon of matchingIcons) {
      if (baseDomain.includes(icon.toLowerCase())) return icon;
    }

    return null;
  } catch {
    return null;
  }
}
